name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: |
        cd client
        npm install

    - name: Build the project
      run: |
        cd client
        npm run build
        ls

    - name: Set Permissions for Private Key
      run: |
        mkdir -p ~/.ssh
        echo "-----BEGIN RSA PRIVATE KEY-----
        MIIEpAIBAAKCAQEAjw1NvilzncD+cefoLRtLTVLPr2iHgHTfMULXXkI2JggPBCo/
        QLADrNsLoJYW35kfr1KoVKsIyTdhc86PruikyThZF2tg73W6Kwe2+l0XK6tDoeaF
        c5ksxzw8pPQImbz6rOzOD/1lw0lQro4C1VUV6DTnunfXFawvMksam8u15kgboeZ8
        XPIIfZqrEixyiqMVt6+SgVJeMxCGb5jRF+s1rMQhXFXx1MV8nqMZQvmCXNlqksRN
        J7qf4iZsQQXQS6vUp3QV7RoKC4wnNu2+DDWLPGNR6VORgP4tWrvWEERw4enE2OCd
        dQpTrOW8pHN3OWqZBMozRiRNoCduMmbdOSIQ/wIDAQABAoIBAHKVB2aAMVl00tpO
        FUy8Bg8De9NWeOLNulDs5zFa+6Bu6AhABrY7xlXYhnG0htHHBvgZzzcyYDE8KNTn
        6XMCaau7dLErk1N7CwmYfln/4qVZ4yx1RwOW96UGfNTrm0/5bRjB/TQVlkNcIEIR
        Aff61TdP2SUlBKUZbBxux/tuql6uwvjmnVvpGNgxCJ+97qXKZzNgRQhKiPxBJ6WR
        qZIa+IQjY+qsf4Js5IHtHXjh0iJITfMntp/5J/JPji/gWFNRCLLHyHoj8tXzzgjK
        qzU6BOqeIWxzJFDaVGnIxiEKcFKUBeepjU4KxORCNalNmrreQmCtkJp+wHYJ8CDb
        4Mk2mFECgYEA1ZCoxttVevqwmCKPjbA0aNrbGCfvz2pj6uHxFZ8HWpdziPF7Z1XX
        gka5JqxO0rOFdhn86Us15pxDpe4fmcdlTRfzfz0W85DMO3ZvhGhAQo0rZwTLcG6q
        rIZfHHBWhVDUDIOoV9bCrqk5E80WXMsL8bbuV9uHBGCnFYUFN1k8g90CgYEAq3ng
        6blUvm26+GmWXfG6cgBYVVx1np6lT//NwXFHmg0h0T2u5yjGZ0a15WldffeFA5Am
        XuX9e229tYB3CqgpZ9BXWD78idglYvdLZlJdOeof2wBdj6qftfxMBwyDJFs77pBZ
        IHMeytpX8OmHPPnICLKuVM7kqtPylpksEt/U2IsCgYEArCJP1xA8QsZChiz9Fc/b
        PlSAWWT/JmfzJwN7xNiMHdmK" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        eval "$(ssh-agent -s)"
        ssh-add ~/.ssh/id_rsa

    - name: Copy build artifacts
      run: |
        cp -r client/dist $GITHUB_WORKSPACE/dist

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: 3.95.189.168
        username: ubuntu
        key: ~/.ssh/id_rsa
        port: 22
        script: |
          # Commands to copy build files to the EC2 server
          scp -i ~/.ssh/id_rsa -r $GITHUB_WORKSPACE/dist/* ubuntu@3.95.189.168:/var/www/Greenback-Claims-main/client/dist
