name: Build and Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16' # Specify the Node.js version you want to use

    - name: Change directory and Install dependencies
      run: |
        cd client
        npm install

    - name: Build the project
      run: |
        cd client
        npm run build
        ls

    # Add additional steps if you want to deploy or further process the build artifacts
