name: Build and Deploy

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: |
        cd client
        npm install

    - name: Build the project
      run: |
        cd client
        npm run build
        ls

    - name: Copy build files to EC2 instance
      run: |
        sudo apt-get install -y sshpass
        sshpass -p 'UtOKdIDiA4wrEVK' scp -o StrictHostKeyChecking=no -r client/dist/* ubuntu@3.95.189.168:/var/www/Greenback-Claims-main/
